### PR TITLE
Fix invalid memory access and now 4 tests fail

### PR DESCRIPTION
**Pull request by asartori86**
I fixed a couple of invalid memory access pointed out by valgrind. Now the four recent tests fail. They run fine, but the output are a bit different, e.g.
```
$ numdiff -a 1e-6 -r 1e-8 -s ' \t\n=,:;<>[](){}^' /home/alberto/opt/src/geotop/tests/1D/Matsch_B2_Ref_007/output-tabs-METEOIO-OFF/basin.txt /home/alberto/opt/src/geotop/tests/1D/Matsch_B2_Ref_007/output-tabs/basin.txt
----------------
##85      #:28  <== 0.000658
##85      #:28  ==> 0.000657
@ Absolute error = 1.0000000000e-6, Relative error = 1.5220700152e-3
----------------
##90      #:28  <== 0.000044
##90      #:28  ==> 0.000043
@ Absolute error = 1.0000000000e-6, Relative error = 2.3255813953e-2
----------------
##112     #:28  <== 0.000949
##112     #:28  ==> 0.000948
@ Absolute error = 1.0000000000e-6, Relative error = 1.0548523207e-3
----------------
##118     #:28  <== 0.000063
##118     #:28  ==> 0.000062
@ Absolute error = 1.0000000000e-6, Relative error = 1.6129032258e-2
```

If I set the absolute tolerance of `numdiff` to `1e-5` everything is fine. Can I update the output of the tests?

### CODE REVIEW

**Comment by cozzini** [comment]
Please, go ahead ! 
upload new output !

**Comment by ssenoner** [comment]
I see there are also some bigger differences in B2_BeG, lowest layer in psiz, BeG is @yakopuz , what do you think about this?

**Comment by ssenoner** [comment]
By the way, @asartori86 , in this commit: https://github.com/geotopmodel/geotop/commit/76301a2636f53748665749eeb245025e3f7b37b1 
I added a generic tolerance for tabs file of 0.0002  :-)
Maybe you want to improve/revert it

**Comment by yakopuz** [comment]
It Is something already investgated Buon Emanuele

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
