### PR TITLE
silence warnings

### PR DESCRIPTION
**Pull request by asartori86**
please do not care about indentation. I'll submit a PR where we can indent with astyle (clang-format is still unstable..)

### CODE REVIEW

**Comment by asartori86** [comment]
a couple of 3D tests hangs.. I'll dig into that

**Comment by ssenoner** [comment]
Hi,
First thing, great job in this branch!!!!!!
I don't thing the 3D jobs just hang.... 
Two are the longest ones, 
but since the code runs much slower now,
Compare travis build 293 and 299,
they don't return in time.
Do you think you can check why fixing the compiler warnings, the code runs slower?

**Comment by asartori86** [comment]
@ssenoner, 
the code runs slower because I erroneously moved the call to `project(geotop)` before we set the `CMAKE_BUILD_TYPE` variable to `RELEASE`. So, the code runs slower because is compiled without the optimization flags :)

I plan to finish this PR today or tomorrow

**Comment by asartori86** [comment]
@cozzini @ssenoner,
I am done. 

I changed the `config.h.in` since it was equal to `version.h.in`. In the actual `config.h.in` I defined several macros. Ideally, in that file we should collect the options set through CMake.

**Pull request merged**
