### PR TITLE
Fixed WARNING in cmake gui after FindBoost.cmake update

### PR DESCRIPTION
**Pull request by sidereus3**
Added Minimum version of Boost library for FindBoost.cmake in order to avoid WARNING before building GEOtop

### CODE REVIEW

**Comment by ssenoner** [comment]
Hi Francesco,
is boost 1.54 also enough?

Greetings

Samuel

**Comment by sidereus3** [comment]
Hi Samuel,

yes, I think so. I just fixed 1.55 only to fix the annoying warnig. That
version should be fine as well.

francesco

**Comment by ssenoner** [comment]
I don't know which warning you are referring to ;-)
the fact regarding 1.54 is that travis by Default has boost 1.46,
Setting travis to ubuntu 14 gives you a newer Version of boot, 1.54,
still not the Version you require... ;-)

Greetings

Samuel

**Comment by sidereus3** [comment]
I got it. I'm running Arch and the new version of FIND BOOST module returns
annoying warnings if you don't specify the minimum version of boost
required (I remember that, but I'm not sure). Thus, I fixed to 1.55 which
is the version by default on Debian Jessie. That's the reason. But I think
you could also fix to 1.46, doesn't really matter I guess.

francesco

**Comment by asartori86** [comment]
@sidereus3,

could you please provide more details? Note that you PR fix the version of boost at **exactly** 1.55 tough.

I tested the library on 3 different distros: gentoo, arch linux, and ubuntu (travis) and I never got a warning.

What version of cmake do you have?

**Comment by cozzini** [comment]
I close this old one

**Pull request closed without merging**
