### PR TITLE
fix failing test

### PR DESCRIPTION
**Pull request by asartori86**
commit 5a49d66 made one test fail. I suppose @cozzini forgot to update the corresponding tabs and maps.. Am I wrong?

BTW I uploaded the new tabs and maps as generated on my laptop

### CODE REVIEW

**Comment by asartori86** [comment]
looks like Travis doesn't like my output.. @cozzini what could we do?

**Comment by ssenoner** [comment]
Hi Alberto, I added once 
CTEST_OUTPUT_ON_FAILURE=TRUE
to travis.yml, you commented it, it will give a hint :-)

**Comment by cozzini** [comment]
Solved in #47

**Comment by ssenoner** [comment]
@asartori86  how did you manage to fix it in 47 and not here?
I don't see much difference....
 This is in fact a problem we had often

**Comment by asartori86** [comment]
@ssenoner, in this PR I uploaded 4 more files that were not needed :(

**Pull request closed without merging**
